const express = require("express")
const routes = express.Router()
const adminCtl = require("../controller/adminCtl")

routes.get("/", adminCtl.index)
routes.get("/charts", adminCtl.charts)
routes.get("/widgets", adminCtl.widgets)
routes.get("/tables",  adminCtl.tables)
routes.get("/grid", adminCtl.grid)
routes.get("/formBasic", adminCtl.formBasic)
routes.get("/formWizard", adminCtl.formWizard)
routes.get("/pagesButtons", adminCtl.pagesButtons)
routes.get("/iconMaterial", adminCtl.iconMaterial)
routes.get("/iconFontAwesome", adminCtl.iconFontAwesome)
routes.get("/pagesElements", adminCtl.pagesElements)
routes.get("/index2", adminCtl.index2)
routes.get("/pagesGallery", adminCtl.pagesGallery)
routes.get("/pagesCalendar", adminCtl.pagesCalendar)
routes.get("/pagesInvoice", adminCtl.pagesInvoice)
routes.get("/pagesChat", adminCtl.pagesChat)
routes.get("/authenticationLogin", adminCtl.authenticationLogin)
routes.get("/authenticationRegister", adminCtl.authenticationRegister)
routes.get("/error403", adminCtl.error403)
routes.get("/error404", adminCtl.error404)
routes.get("/error405", adminCtl.error405)
routes.get("/error500", adminCtl.error500)

module.exports = routes